name: Rose Hoffmann
favicon: null
layout_spectrum: 0.63563
typography_spectrum: 0.7811517361551523
title: Rose Hoffmann Art
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cc5c84'
    - '#dfc7d7'
    - '#8ab192'
    - '#000002'
    - '#518962'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
